# Generated by Django 3.0.5 on 2020-04-26 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineplayer',
            name='monitoring_user',
            field=models.ForeignKey(limit_choices_to={'user_type__in': [1, 2, 3, 4]}, on_delete=django.db.models.deletion.PROTECT, related_name='onlineplayer_moniter', to=settings.AUTH_USER_MODEL),
        ),
    ]
