# Generated by Django 3.0.5 on 2020-05-02 08:24

from django.db import migrations
import django_cryptography.fields
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20200426_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalagentplayersuperpotbet',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalagentplayersuperpotbet',
            name='player',
        ),
        migrations.RemoveField(
            model_name='historicalagentplayersuperpotbet',
            name='pot',
        ),
        migrations.RemoveField(
            model_name='historicalagentplayersuperpotbet',
            name='slip',
        ),
        migrations.RemoveField(
            model_name='historicalagentplayersuperpotbet',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='historicalonlineplayersuperpotbet',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalonlineplayersuperpotbet',
            name='player',
        ),
        migrations.RemoveField(
            model_name='historicalonlineplayersuperpotbet',
            name='pot',
        ),
        migrations.RemoveField(
            model_name='historicalonlineplayersuperpotbet',
            name='slip',
        ),
        migrations.RemoveField(
            model_name='historicalonlineplayersuperpotbet',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='historicalsuperpot',
            name='event',
        ),
        migrations.RemoveField(
            model_name='historicalsuperpot',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsuperpotevent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalsuperpotevent',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsuperpotslip',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='onlineplayersuperpotbet',
            name='player',
        ),
        migrations.RemoveField(
            model_name='onlineplayersuperpotbet',
            name='pot',
        ),
        migrations.RemoveField(
            model_name='onlineplayersuperpotbet',
            name='slip',
        ),
        migrations.RemoveField(
            model_name='onlineplayersuperpotbet',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='superpot',
            name='event',
        ),
        migrations.RemoveField(
            model_name='superpotevent',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='agent',
            name='bank_details',
            field=django_cryptography.fields.encrypt(jsonfield.fields.JSONField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_details',
            field=django_cryptography.fields.encrypt(jsonfield.fields.JSONField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='bank_details',
            field=django_cryptography.fields.encrypt(jsonfield.fields.JSONField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='bank_details',
            field=django_cryptography.fields.encrypt(jsonfield.fields.JSONField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='historicalmanager',
            name='bank_details',
            field=django_cryptography.fields.encrypt(jsonfield.fields.JSONField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='historicalonlineplayer',
            name='bank_details',
            field=django_cryptography.fields.encrypt(jsonfield.fields.JSONField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='historicalsupervisor',
            name='bank_details',
            field=django_cryptography.fields.encrypt(jsonfield.fields.JSONField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='manager',
            name='bank_details',
            field=django_cryptography.fields.encrypt(jsonfield.fields.JSONField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='onlineplayer',
            name='bank_details',
            field=django_cryptography.fields.encrypt(jsonfield.fields.JSONField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='bank_details',
            field=django_cryptography.fields.encrypt(jsonfield.fields.JSONField(blank=True, null=True)),
        ),
        migrations.DeleteModel(
            name='AgentPlayerSuperPotBet',
        ),
        migrations.DeleteModel(
            name='HistoricalAgentPlayerSuperPotBet',
        ),
        migrations.DeleteModel(
            name='HistoricalOnlinePlayerSuperPotBet',
        ),
        migrations.DeleteModel(
            name='HistoricalSuperPot',
        ),
        migrations.DeleteModel(
            name='HistoricalSuperPotEvent',
        ),
        migrations.DeleteModel(
            name='HistoricalSuperPotSlip',
        ),
        migrations.DeleteModel(
            name='OnlinePlayerSuperPotBet',
        ),
        migrations.DeleteModel(
            name='SuperPot',
        ),
        migrations.DeleteModel(
            name='SuperPotEvent',
        ),
        migrations.DeleteModel(
            name='SuperPotSlip',
        ),
    ]
