# Generated by Django 3.0.5 on 2020-05-03 14:53

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsuperpotevent',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(None, '---- default(Everyday) ----'), ('sunday', 'sunday'), ('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday')], max_length=61, null=True),
        ),
        migrations.AddField(
            model_name='historicalsuperpotevent',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalsuperpotevent',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalsuperpotevent',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superpotevent',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(None, '---- default(Everyday) ----'), ('sunday', 'sunday'), ('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday')], max_length=61, null=True),
        ),
        migrations.AddField(
            model_name='superpotevent',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superpotevent',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='superpotevent',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agentplayersuperpotbet',
            name='slip',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='historicalagentplayersuperpotbet',
            name='slip',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalonlineplayersuperpotbet',
            name='slip',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onlineplayersuperpotbet',
            name='slip',
            field=models.CharField(max_length=12),
        ),
        migrations.DeleteModel(
            name='HistoricalSuperPotSlip',
        ),
        migrations.DeleteModel(
            name='SuperPotSlip',
        ),
    ]
