# Generated by Django 2.2 on 2020-02-13 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superpotevent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='superpotevent_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='superpot',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='superpot_event', to='games.SuperPotEvent'),
        ),
        migrations.AddField(
            model_name='onlineplayersuperpotbet',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onlineplayersuperpotbet_player', to='master.OnlinePlayer'),
        ),
        migrations.AddField(
            model_name='onlineplayersuperpotbet',
            name='pot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onlineplayersuperpotbet_pot', to='games.SuperPot'),
        ),
        migrations.AddField(
            model_name='onlineplayersuperpotbet',
            name='slip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onlineplayersuperpotbet_slip', to='games.SuperPotSlip'),
        ),
        migrations.AddField(
            model_name='onlineplayersuperpotbet',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='onlineplayersuperpotbet_transaction', to='payments.OnlinePlayerBalanceAccount'),
        ),
        migrations.AddField(
            model_name='internationalpot',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internationalpot_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internationalpot',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internationalpot_game', to='games.Game'),
        ),
        migrations.AddField(
            model_name='historicalsuperpotslip',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsuperpotevent',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsuperpotevent',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsuperpot',
            name='event',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='games.SuperPotEvent'),
        ),
        migrations.AddField(
            model_name='historicalsuperpot',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalonlineplayersuperpotbet',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalonlineplayersuperpotbet',
            name='player',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master.OnlinePlayer'),
        ),
        migrations.AddField(
            model_name='historicalonlineplayersuperpotbet',
            name='pot',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='games.SuperPot'),
        ),
        migrations.AddField(
            model_name='historicalonlineplayersuperpotbet',
            name='slip',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='games.SuperPotSlip'),
        ),
        migrations.AddField(
            model_name='historicalonlineplayersuperpotbet',
            name='transaction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payments.OnlinePlayerBalanceAccount'),
        ),
        migrations.AddField(
            model_name='historicalinternationalpot',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinternationalpot',
            name='game',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='games.Game'),
        ),
        migrations.AddField(
            model_name='historicalinternationalpot',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgame',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalclubteam',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalclubpot',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalclubpot',
            name='game',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='games.Game'),
        ),
        migrations.AddField(
            model_name='historicalclubpot',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalclubpot',
            name='team_1',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='games.ClubTeam'),
        ),
        migrations.AddField(
            model_name='historicalclubpot',
            name='team_2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='games.ClubTeam'),
        ),
        migrations.AddField(
            model_name='historicalclubpot',
            name='winning_team',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='games.ClubTeam'),
        ),
        migrations.AddField(
            model_name='historicalagentplayersuperpotbet',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalagentplayersuperpotbet',
            name='player',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master.AgentPlayer'),
        ),
        migrations.AddField(
            model_name='historicalagentplayersuperpotbet',
            name='pot',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='games.SuperPot'),
        ),
        migrations.AddField(
            model_name='historicalagentplayersuperpotbet',
            name='slip',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='games.SuperPotSlip'),
        ),
        migrations.AddField(
            model_name='historicalagentplayersuperpotbet',
            name='transaction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payments.AgentBalanceAccount'),
        ),
        migrations.AddField(
            model_name='clubpot',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clubpot_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubpot',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clubpot_game', to='games.Game'),
        ),
        migrations.AddField(
            model_name='clubpot',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clubpot_team_1', to='games.ClubTeam'),
        ),
        migrations.AddField(
            model_name='clubpot',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clubpot_team_2', to='games.ClubTeam'),
        ),
        migrations.AddField(
            model_name='clubpot',
            name='winning_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clubpot_win_team', to='games.ClubTeam'),
        ),
        migrations.AddField(
            model_name='agentplayersuperpotbet',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agentplayersuperpotbet_player', to='master.AgentPlayer'),
        ),
        migrations.AddField(
            model_name='agentplayersuperpotbet',
            name='pot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agentplayersuperpotbet_pot', to='games.SuperPot'),
        ),
        migrations.AddField(
            model_name='agentplayersuperpotbet',
            name='slip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agentplayersuperpotbet_slip', to='games.SuperPotSlip'),
        ),
        migrations.AddField(
            model_name='agentplayersuperpotbet',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='agentplayersuperpotbet_transaction', to='payments.AgentBalanceAccount'),
        ),
    ]
